version: '2'
services:
  couchdb:
    image: couchdb
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER_NAME}
      - COUCHDB_PASSWORD=${COUCHDB_USER_PASS}
    volumes:
      - couchdb_dados:/usr/local/var/lib/couchdb
    ports:
      - "${HOST_COUCHDB_PORT}:5984"
  fauxton:
    image: 3apaxicom/fauxton
    restart: always
    ports:
      - "${HOST_FAUXTON_PORT}:8000"
    links:
      - couchdb:db
    command:
      - sh
      - "-c"
      - "fauxton -c http://db:5984"